### ISSUE TITLE
Make the push registration call voice repeat the number at least once

### ISSUE THREAD

**Issue by SpiritQuaddicted** [WhisperSystems/TextSecure-Server#18]
The 6 letter number you are told when using the "confirmation by call" for the push registration is only said once. Unless you know that beforehand and write it down quickly or if you have a good talent of quickly memorising the numbers you are in a bad situation and will probably need to toggle another call.

Please make the numbers be repeated at least once so slower people have a change of using that service successfully. Or announce them slower.

Originally posted at https://github.com/WhisperSystems/TextSecure/issues/1698
Closed as it was not the right place. If this is the wrong place again, please be so nice to use your superior knowledge of the project to copy this issue to the right place when closing it. Thanks!

**Comment by patcon** [comment]
Great idea.

https://github.com/WhisperSystems/TextSecure-Server/blob/master/src/main/java/org/whispersystems/textsecuregcm/sms/TwilioSmsSender.java#L43

https://www.twilio.com/docs/api/twiml/say#attributes-loop
