### ISSUE TITLE
Increase connection timeout

### ISSUE THREAD

**Issue by JavaJens** [WhisperSystems/TextSecure-Server#27]
Since recently the connection timeout was lowered s.t. connections timeout after ~30s.
This was accounted for by iOS client and recently the Browser implementation (https://github.com/WhisperSystems/TextSecure-Browser/issues/97).

In the investigation of websocket support on android (https://github.com/WhisperSystems/TextSecure/issues/1000), it was noticed that a heartbeat of 30s drastically reduces battery life and the best solution towards optimal battery usage would be a dynamic heartbeat mechanism based on the current network solution.

Therefore I think that the timeout on the connection should not primarily be limited by the server, but by the capabilities of the clients network connection.

**Comment by moxie0** [comment]
We also have to mind the server resources.
