### ISSUE TITLE
TS user still present in group chat after unregister causes error messages

### ISSUE THREAD

**Issue by DrGrill0r** [WhisperSystems/TextSecure-Server#30]
When unregistering from TextSecure push service via https://whispersystems.org/textsecure/unregister/ the contact seems not to be removed from the groups he is in. This causes really annoying "message could not be delivered" error messages for every single message one sends to the group.

Since removing group members is not possible the only two solutions to this problem are either to leave the group and create a new one or re-registering the missing user. Issue encountered using TextSecure Client v2.4.1.

**Comment by liliakai** [comment]
The server has no knowledge of groups. This issue will have to be solved on the clientside.

**Comment by rmueller83** [comment]
See https://github.com/WhisperSystems/TextSecure/issues/2408
