### ISSUE TITLE
Is websocket message deliver already added instead of GCM? 

### ISSUE THREAD

**Issue by al11al** [WhisperSystems/TextSecure-Server#31]
Hello!

We would like to use TextSecure server and client technologies to improve our existing message system. We are interested mostly in speed of delivery. I have found here http://support.whispersystems.org/customer/portal/questions/8542401-where-did-my-textsecure-messages-go-for-3-hours-2-still-waiting-for-answer that WebSockets support for Android devices should be added. Has it been implemented already? Couldn't not find proper commit description in repo.

Thanks in advance.

**Comment by JavaJens** [comment]
AFAIK it is implemented in the following way: if TextSecure is visible a websocket connection to the server is maintained, if not GCM is used to trigger the establishment of a connection.

**Comment by al11al** [comment]
Thanks you JavaJens, your answer is very helpful.

**Comment by moxie0** [comment]
@al11al This is an issue tracker, not a support or discussion forum.
