### ISSUE TITLE
Error while running server "local.yml has an error"

### ISSUE THREAD

**Issue by supportreq** [WhisperSystems/TextSecure-Server#33]
Hi,

I followed the wiki steps of configuring my own textsecure-server on an ubuntu 14.04 server [with orcale jdk 8].
JAR was created successfully, ran the following command : 
# java -jar target/TextSecureServer-0.40.jar accountdb migrate local.yml
local.yml has an error:
  * Unrecognized field at: gcm
    Did you mean?:
      - s3
      - cache
      - nexmo
      - push
      - limits
        [12 more]

Please advice..

The local.yml file : 
=================
twilio:
  accountId: xxxxxxxxxx
  accountToken: xxxxxxxxxxx
  number: 1xxxxxxxxxx
  localDomain: https://ipaddress # The domain Twilio can call back to.
  international: 1 # Boolean specifying Twilio for international delivery

# Optional. If specified, Nexmo will be used for non-US SMS and 
# voice verification if twilio.international is false. Otherwise,
# Nexmo, if specified, Nexmo will only be used as a fallback
# for failed Twilio deliveries.
#nexmo:
 # apiKey:
  #apiSecret:
  #number:

gcm:
  senderId: xxxxxxxx
  apiKey: xxxxxxxxx

# Optional. Only if iOS clients are supported.
apn:
  # In PEM format.
  certificate: 
  
  # In PEM format.
  key: 

s3:
  accessKey: xxxxxx
  accessSecret: xxxxxxx

  # Name of the S3 bucket (needs to have been created)
  # for attachments to go.  Should be configured with
  # correct permissions.
  attachmentsBucket:xxxx

memcache:
  servers: 
  user: 
  password: 

redis:
  url: ipaddress:6379

federation:
  name:
  peers: 
    -
      name: somepeer
      url: https://foo.com
      authenticationToken: foo
      certificate: in pem format 

# Optional address of graphite server to report metrics
graphite:
  host:
  port:

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: postgres

  # the password
  password: postgres

  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/mydb

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
=================

please advice

**Comment by JavaJens** [comment]
I'm sure moxie is going to close this as this is not a support forum.
Eitherway I'd say look into the other repositories, AFAIK the push stuff is in its own repository and hence configuration changed.

**Comment by moxie0** [comment]
This is not a support forum.
