### ISSUE TITLE
Ability to easily send mock messages

### ISSUE THREAD

**Issue by patcon** [WhisperSystems/TextSecure-Server#34]
While reading through the textsecure issue queue, started wondering how we can create a simple way to make issues more reproducible. Would a CLI tool that can be run on the server be worthwhile? It's just that it's not always simple to get a friend to play along, or to use another phone number/device.

Not sure if I'll have time to try to understand the framework, but thought it would be nice to have easier testing, perhaps using vagrant, this in-progress [chef-textsecure cookbook](https://github.com/patcon/chef-textsecure), and the [ngrok cookbook](https://github.com/onbeep-cookbooks/ngrok)

**Comment by patcon** [comment]
Should I have posted to mailing list? :) 

I appreciate that you're really busy, but it's a little discouraging to get shut down without any context. As in, I don't know what to think -- was my thought stupid? Did I not follow process? Should I submit code first so they know I care enough? Do I dig deeper to find out why it was so easily dismissed, or just give up right away?

**Comment by moxie0** [comment]
This issue tracker is not a discussion forum, it is only for tracking bugs.  If you have things you'd like to discuss, the mailing list is probably the best place.
