### ISSUE TITLE
inter server communication

### ISSUE THREAD

**Issue by Maesto** [WhisperSystems/TextSecure-Server#36]
Just throwing this Idear in the Room.
I guess this would be quite diffucult. Cause a server would need to know which (other) server is responsible for a number. But maybe someone has a good Idea how to handle such a case.

I also guess that it would only be of use for advanced Users. And maybe it would be easyer to give the client multiple servers with a priority?

**Comment by moxie0** [comment]
That's already supported, but this is not a discussion forum.
