### ISSUE TITLE
Source being saved on server

### ISSUE THREAD

**Issue by danielschonfeld** [WhisperSystems/TextSecure-Server#37]
I am trying to figure out if there's a value to storing the source information along with the message or if there's any usage (I couldn't find, but maybe i didn't dive deep enough into the code) for sending the source information at all when submitting a message.

If not I think there's a chance of optimizing the protocol here by encrypting the source, and counter metadata with the axolotl master key.  

- It makes us even more immune to being queries for metadata about two parties having a conversation 
- It seems like a relatively cheap extra step on the client side to decrypt while giving us the advantage of the above

**Comment by moxie0** [comment]
Hey @danielschonfeld, this isn't a discussion forum, so it'd be more appropriate for you to post discussion items on a mailing list. The short answer to your question is rate limiting and abuse, and ideas for preserving that capability along with metadata hiding have been talked about fairly extensively on the moderncrypto messaging list. It's probably something we'll do eventually.
