### ISSUE TITLE
support for integration testing infrastructure

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure-Server#40]
I propose that the following endpoints be modified for the purpose of supporting integration testing infrastructure:

## GET /v1/accounts/{transport}/code/{number}

On our staging deployment, for all requests where `number` is a valid PSTN number with country code prefix `+963` (Syria), the server should respond `200` but not attempt to initiate SMS or voice verification with the client.

## PUT /v1/acccounts/code/{verification_code}

On our staging deployment, for all requests where the `number` field within the `Authorization` header is a valid PSTN number with country code prefix `+963` (Syria), the server should always consider `verification_code` to be valid.

**Comment by moxie0** [comment]
give me a set of fully qualified numbers mapped to their verification codes, rather than a whole country and any code

**Comment by rhodey** [comment]
I can do that but it is going to be a large set. right now there are something like 40 integration tests and these get run on a dozen or more devices simultaneously. we can't have two tests using the same number at the same time so we need at least one PSTN number per device, client side this would have to be a map of Android version + device model => PSTN number => code.

I'll start off with a dozen of my favorite TestObject devices and format the set so it can be thrown into yaml.

**Comment by rhodey** [comment]
this set is enough to test every possible API level on TestObject.

```
+963315666555 => 002-2014
+16085555555  => 005-2014
+97022555555  => 007-2014
+17185555555  => 007-2014
+13145555555  => 008-2014
+12165555555  => 011-2014
+17035555555  => 012-2014
+963315555555 => 001-2015
+9671555555   => 003-2015
+96732555555  => 004-2015
+496371475555 => 004-2015
+14105555555  => 005-2015
+15555555555  => 5555-5555
```

moving to a static whitelist approach means I'll also need the rate limits ignored for these numbers as well, not just for the above two endpoints but for things like contact intersection too. moving forward I can:

1) enumerate every endpoint that needs rate limit adjustments
2) grow the whitelist so large it is statistically unlikely that rate limits will be exceeded
3) go back to the country code / block allocation idea
