### ISSUE TITLE
Provide a GCM alternative (but seriously this time)

### ISSUE THREAD

**Issue by 12foo** [WhisperSystems/TextSecure-Server#52]
First off, I promise the following isn't going to happen:
```
@12foo: moxie, can you guys make Signal run on non-Google phones for me?
@moxie0: <nth repeat of well-reasoned argument>
@12foo: okay, but can you make Signal run on non-Google phones for me?
```
I'm on a non-Google phone, so I'd really appreciate a non-GCM solution. I've thought about it a bit (and started coding a little), but before I go further I'd like to check if this is something that's actually workable. Basically there's a service called [pushy](https://pushy.me) that offers a paid alternative to GCM at quite reasonable rates ($0.005 per device-month). I would like to:

1. Abstract push messaging to something more generic than hard-coded GCM and APN so it's extensible (that's what I've started work on).
2. Extend push messaging to support pushy (and maybe websockets as its own separate "push" service instead of piggybacking on GCM).
3. Put in a whitelist functionality that allows whitelisting of supported phone numbers on certain push services, either via database table or (my preference) a query to an external HTTPS server. If a phone tries to register as a push receiver on that service and the whitelist check fails, the phone can not register.
4. Set up a donation server or couple with existing donations to OpenWhisperSystems so that donations of at least $5 can unlock a single phone number for pushy. The donation server only receives the money, checks it's a valid number, and adds it to the white list. No other personally identifying information is collected.

I think $5 or $10 is a reasonable amount to ask because it's intended to be a bit of a deterrent. $5 is a little more than 83 device-years on pushy, so that one-time payment should cover lifetime usage and leave extra money for the project. I realize this requires quite a bit of buy-in from OpenWhisperSystems, so that's why I'd like to check and collect criticism first. If that's not a workable solution for the project itself, maybe it can be done by someone running a federated server using this sort of plan.

**Comment by moxie0** [comment]
thanks but we're not going to do this
