### ISSUE TITLE
Websocket error 405 - HTTP Error 405 Method not allowed

### ISSUE THREAD

**Issue by dnemov** [WhisperSystems/TextSecure-Server#58]
Android app when is opened  in the server logs appears those messages

	192.168.1.18 - - [03/дек/2015:14:04:26 +0000] "GET /v1/websocket/?login=XXX&password=NJC2Qd3nbDcullkCEQNISwV/ HTTP/1.1" 405 367 "-" "okhttp/2.2.0" 10
	192.168.1.18 - - [03/дек/2015:14:04:29 +0000] "GET /v1/websocket/?login=XXX&password=NJC2Qd3nbDcullkCEQNISwV/ HTTP/1.1" 405 367 "-" "okhttp/2.2.0" 2
	192.168.1.18 - - [03/дек/2015:14:04:32 +0000] "GET /v1/websocket/?login=XXX&password=NJC2Qd3nbDcullkCEQNISwV/ HTTP/1.1" 405 367 "-" "okhttp/2.2.0" 1

TextSecure Server stay behind apache2 reverse proxy  

Removing those strings from src/main/java/org/whispersystems/textsecuregcm/WhisperServerService.java doesnt give any result

	FilterRegistration.Dynamic filter = environment.servlets().addFilter("CORS", CrossOriginFilter.class);
	filter.addMappingForUrlPatterns(EnumSet.allOf(DispatcherType.class), true, "/*");
	filter.setInitParameter("allowedOrigins", "*");
	filter.setInitParameter("allowedHeaders", "Content-Type,Authorization,X-Requested-With,Content-Length,Accept,Origin");
	filter.setInitParameter("allowedMethods", "GET,PUT,POST,DELETE,OPTIONS");
	filter.setInitParameter("preflightMaxAge", "5184000");
	filter.setInitParameter("allowCredentials", "true");

Full debug server log
[Server.log.txt](https://github.com/WhisperSystems/TextSecure-Server/files/50890/Server.log.txt)

**Comment by moxie0** [comment]
Sorry, this isn't a support forum, please don't post questions here.
