### ISSUE TITLE
Cannot connect to TextSecure-Server

### ISSUE THREAD

**Issue by PinkPhayate** [WhisperSystems/TextSecure-Server#69]
I am building an application as like this.
I'd like to change server from TextSecure-Server to another server built in my machine.
I send phone number from my iOS device to another server via http in order to return verification code.
But server shows error message 

org.eclipse.jetty.http.HttpParser: Illegal character 0x16 in state=START for buffer

So I presume that I must send phone number to server via https.
Thus, I want to enable server to connect via https. 
TextSecure-Server is made by Jetty. So I look for Jetty in order to locate "jetty-ssl.xml", "jetty-https.xml" and pom.xml which enable to receive via https.
But I cannot find Jetty files.

Could you tell me how can i solve this issue ?

**Comment by moxie0** [comment]
sorry this isn't a discussion forum
